package bookshop;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class BookShop extends javax.swing.JFrame {

    public BookShop() {
        initComponents();
        initialize();
        Connect();
        table_load();
    }

    public final void initialize() {
        setTitle("Dashboard");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(900, 600);
        setMinimumSize(new Dimension(900, 600));
        setLocationRelativeTo(null);
        setVisible(true);
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public final void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/bookshop", "root", "2711");
        } catch (ClassNotFoundException | SQLException ex) {

        }
    }

    public final void table_load() {
        try {
            pst = con.prepareStatement("SELECT * FROM book");
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBMS = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        lbPrice = new javax.swing.JLabel();
        lbEdition = new javax.swing.JLabel();
        lbBookName = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        tfEdition = new javax.swing.JTextField();
        tfBName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        bntClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        panelSearch = new javax.swing.JPanel();
        tfBId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBMS.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        lbBMS.setText("Book Management System");
        getContentPane().add(lbBMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        panelRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 18))); // NOI18N
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPrice.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lbPrice.setText("Price");
        panelRegister.add(lbPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lbEdition.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lbEdition.setText("Edition");
        panelRegister.add(lbEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lbBookName.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lbBookName.setText("Book Name");
        panelRegister.add(lbBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        tfPrice.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        tfPrice.setText("\n");
        tfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPriceActionPerformed(evt);
            }
        });
        panelRegister.add(tfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, -1));

        tfEdition.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        tfEdition.setText(" ");
        tfEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEditionActionPerformed(evt);
            }
        });
        panelRegister.add(tfEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, -1));

        tfBName.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        tfBName.setText("\n");
        tfBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBNameActionPerformed(evt);
            }
        });
        panelRegister.add(tfBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 220, -1));

        getContentPane().add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 430, 270));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Book Name", "Edition", "Price"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 370, 340));

        btnExit.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnExitKeyReleased(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 130, 60));

        bntClear.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        bntClear.setText("CLEAR");
        bntClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntClearActionPerformed(evt);
            }
        });
        getContentPane().add(bntClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, 60));

        btnSave.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 60));

        btnDelete.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 130, 60));

        btnUpdate.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 130, 60));

        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 0, 18))); // NOI18N
        panelSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfBId.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        tfBId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBIdActionPerformed(evt);
            }
        });
        tfBId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBIdKeyReleased(evt);
            }
        });
        panelSearch.add(tfBId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 230, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Book ID");
        panelSearch.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        getContentPane().add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 430, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyReleased
        // TODO add your handling code here:
        try {
            String cdBId = tfBId.getText();

            pst = con.prepareStatement("SELECT name, edition, price FROM book WHERE id = ?");
            pst.setString(1, cdBId);
            ResultSet rSet = pst.executeQuery();

            if (rSet.next() == true) {
                String cdBName = rSet.getString(1);
                String cdEdition = rSet.getString(2);
                String cdPrice = rSet.getString(3);

                tfBName.setText(cdBName);
                tfEdition.setText(cdEdition);
                tfPrice.setText(cdPrice);
            } else {
                tfBName.setText("");
                tfEdition.setText("");
                tfPrice.setText("");
            }

        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_btnExitKeyReleased

    private void bntClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntClearActionPerformed
        // TODO add your handling code here:
        tfBName.setText("");
        tfEdition.setText("");
        tfPrice.setText("");
        tfBName.requestFocus();
    }//GEN-LAST:event_bntClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String cdBName, cdEdition, cdPrice;
        cdBName = tfBName.getText();
        cdEdition = tfEdition.getText();
        cdPrice = tfPrice.getText();

        try {
            pst = con.prepareStatement("INSERT INTO book(Name, Edition, Price) VALUES(?,?,?)");
            pst.setString(1, cdBName);
            pst.setString(2, cdEdition);
            pst.setString(3, cdPrice);
            pst.executeUpdate();
            JOptionPane.showInternalMessageDialog(null, "Record Added!!!!");
            table_load();
            tfBName.setText("");
            tfEdition.setText("");
            tfPrice.setText("");
            tfBName.requestFocus();
        } catch (SQLException e1) {
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String cdBId;
        cdBId = tfBId.getText();

        try {
            pst = con.prepareStatement("DELETE FROM book WHERE Id = ?");
            pst.setString(1, cdBId);
            pst.executeUpdate();
            JOptionPane.showInternalMessageDialog(null, "Record Deleted!!!!");
            table_load();
            tfBName.setText("");
            tfEdition.setText("");
            tfPrice.setText("");
            tfBName.requestFocus();
        } catch (SQLException e1) {
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String cdBName, cdEdition, cdPrice, cdBId;
        cdBName = tfBName.getText();
        cdEdition = tfEdition.getText();
        cdPrice = tfPrice.getText();
        cdBId = tfBId.getText();

        try {
            pst = con.prepareStatement("UPDATE book SET Name = ?, Edition = ?, Price = ? WHERE Id = ?");
            pst.setString(1, cdBName);
            pst.setString(2, cdEdition);
            pst.setString(3, cdPrice);
            pst.setString(4, cdBId);
            pst.executeUpdate();
            JOptionPane.showInternalMessageDialog(null, "Record Updated!!!!");
            table_load();
            tfBName.setText("");
            tfEdition.setText("");
            tfPrice.setText("");
            tfBName.requestFocus();
        } catch (SQLException e1) {
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfBIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBIdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfBIdActionPerformed

    private void tfBIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBIdKeyReleased
        // TODO add your handling code here:
        try {
            String cdBId = tfBId.getText();

            pst = con.prepareStatement("SELECT Name, Edition, Price FROM book WHERE Id = ?");
            pst.setString(1, cdBId);
            ResultSet rSet = pst.executeQuery();

            if (rSet.next() == true) {
                String cdBName = rSet.getString(1);
                String cdEdition = rSet.getString(2);
                String cdPrice = rSet.getString(3);

                tfBName.setText(cdBName);
                tfEdition.setText(cdEdition);
                tfPrice.setText(cdPrice);
            } else {
                tfBName.setText("");
                tfEdition.setText("");
                tfPrice.setText("");
            }

        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_tfBIdKeyReleased

    private void tfBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBNameActionPerformed

    private void tfEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEditionActionPerformed

    private void tfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BookShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBMS;
    private javax.swing.JLabel lbBookName;
    private javax.swing.JLabel lbEdition;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfBId;
    private javax.swing.JTextField tfBName;
    private javax.swing.JTextField tfEdition;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
