package bookshop;

import java.awt.*;
import javax.swing.*;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        initialize();
    }

    public final void initialize() {
        setTitle("Login");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(900, 600);
        setMinimumSize(new Dimension(900, 600));
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLoginPage = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        pfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLoginPage.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        lbLoginPage.setText("Login Page");
        getContentPane().add(lbLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        lbPassword.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        lbPassword.setText("Password");
        getContentPane().add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        lbEmail.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        lbEmail.setText("E-mail");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        tfEmail.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 480, -1));

        btnLogin.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 700, -1));

        pfPassword.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 480, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            String cdEmail, cdPassword;
            cdEmail = tfEmail.getText();
            cdPassword = pfPassword.getText();

            if (cdEmail.isEmpty() && cdPassword.isEmpty()) {
                JOptionPane.showInternalMessageDialog(null, "Blank Username or Password!!!!");
            } else if (cdEmail.equals("himanshu.m1802@gmail.com") && cdPassword.equals("123456")) {
                JOptionPane.showInternalMessageDialog(null, "Login Success!!!!");
                BookShop bShop = new BookShop();
                bShop.show();
                dispose();
            } else {
                JOptionPane.showInternalMessageDialog(null, "Login Failed!!!!");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLoginPage;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables
}
